[2025-06-04 13:20:41,238: INFO: main: welcome to my custom log.]
[2025-06-04 16:00:13,187: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:00:13,531: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:00:28,282: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:00:28,285: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:01:43,867: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:01:43,872: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:07:34,661: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:07:34,665: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:09:50,183: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:09:50,186: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:14:25,724: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:14:25,726: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:15:11,522: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:15:11,527: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:16:06,896: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:16:06,899: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:17:17,227: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:17:17,233: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:24:04,821: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:24:04,824: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:27:02,691: INFO: common: yaml file: /home/sdp/python/chicken_disease_classification/config/config.yaml loaded successfully]
[2025-06-04 16:27:02,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:39:48,229: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:39:48,232: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:42:32,034: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:42:32,037: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:42:37,370: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:42:37,374: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:43:45,963: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:43:45,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:52:00,139: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:52:00,143: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:53:25,758: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-06-04 16:53:25,762: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-04 16:53:25,765: INFO: common: created directory at: artifacts]
[2025-06-04 16:53:25,767: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 17:14:47,849: ERROR: stage_01_data_ingestion: name 'DataIngestion' is not defined]
Traceback (most recent call last):
  File "/home/sdp/python/chicken_disease_classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 17, in <module>
    obj.main()
  File "/home/sdp/python/chicken_disease_classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 10, in main
    data_ingestion = DataIngestion(config=ConfigurationManager().get_data_ingestion_config())
                     ^^^^^^^^^^^^^
NameError: name 'DataIngestion' is not defined
[2025-06-04 17:20:01,275: INFO: common: created directory at: artifacts]
[2025-06-04 17:20:01,275: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 17:20:20,451: INFO: common: created directory at: artifacts]
[2025-06-04 17:20:20,452: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 17:20:35,526: INFO: common: created directory at: artifacts]
[2025-06-04 17:20:35,526: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 17:24:13,922: INFO: common: created directory at: artifacts]
[2025-06-04 17:24:13,922: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 20:50:19,138: INFO: font_manager: Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: Can not load face (unknown file format; error code 0x2)]
[2025-06-04 20:50:21,087: WARNING: font_manager: Matplotlib is building the font cache; this may take a moment.]
[2025-06-04 20:50:23,280: INFO: font_manager: generated new fontManager]
[2025-06-04 21:02:22,226: INFO: common: created directory at: artifacts]
[2025-06-04 21:02:22,230: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:04:28,638: INFO: common: created directory at: artifacts]
[2025-06-04 21:04:28,641: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:09:56,519: INFO: common: created directory at: artifacts]
[2025-06-04 21:09:56,521: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:11:12,858: INFO: common: created directory at: artifacts]
[2025-06-04 21:11:12,860: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:14:29,200: INFO: common: created directory at: artifacts]
[2025-06-04 21:14:29,203: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:15:39,464: INFO: common: created directory at: artifacts]
[2025-06-04 21:15:39,465: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:15:43,911: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-04 21:15:44,066: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-04 21:32:46,225: INFO: main: Data Ingestion stage started]
[2025-06-04 21:32:46,228: INFO: common: created directory at: artifacts]
[2025-06-04 21:32:46,228: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 21:32:47,829: INFO: main: Data Ingestion stage completed ]
[2025-06-04 21:32:47,830: INFO: main: Prepare base model started]
[2025-06-04 21:32:47,831: INFO: common: created directory at: artifacts]
[2025-06-04 21:32:47,832: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:32:47,832: ERROR: main: PrepareBaseModelConfig.__init__() got an unexpected keyword argument 'params_batch_size']
Traceback (most recent call last):
  File "/home/sdp/python/chicken_disease_classification/main.py", line 22, in <module>
    prepare_base_model.main()
  File "/home/sdp/python/chicken_disease_classification/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 11, in main
    prepare_base_model_config = ConfigurationManager().get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdp/python/chicken_disease_classification/src/cnnClassifier/config/configuration.py", line 39, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
                                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PrepareBaseModelConfig.__init__() got an unexpected keyword argument 'params_batch_size'
[2025-06-04 21:33:43,511: INFO: main: Data Ingestion stage started]
[2025-06-04 21:33:43,514: INFO: common: created directory at: artifacts]
[2025-06-04 21:33:43,514: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-04 21:33:44,386: INFO: main: Data Ingestion stage completed ]
[2025-06-04 21:33:44,387: INFO: main: Prepare base model started]
[2025-06-04 21:33:44,389: INFO: common: created directory at: artifacts]
[2025-06-04 21:33:44,389: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-04 21:33:44,937: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-04 21:33:45,121: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-06-04 21:33:45,247: INFO: main: Prepare base model completed]
